### ISSUE TITLE
Error when using .Count()

### ISSUE THREAD

**Issue by rafakwolf** [wedeploy/wedeploy-sdk-js#249]
Nodejs: 8.11.3
WeDeploy: 4.5.0

```js
app.post('/add-data', function(req, res) {
	wedeploy.data('https://<my-data>.wedeploy.io')
	 .create('foo', 
			{
			"vpnConfiguration": {
			    "forwardingPorts": [
			      {
			        "host": "192.168.0.2",
			        "port": "80",
			        "internalPort": "30214"
			      },
			      {
			        "host": "192.168.0.3",
			        "port": "80",
			        "internalPort": "30215"
			      }
			    ]
			  }
			}
			).then(function(resp) {
				res.send('saved!');
			}).catch(function(err){
				res.send('ops! nothing happends');
			});
});
```
and then, trying to filtering and count like:

```js
app.get('/get-data', function(req, res) {

    let filter = wedeploy.Filter.equal('vpnConfiguration.forwardingPorts.host', '192.168.0.3')
    			                .and('vpnConfiguration.forwardingPorts.port', '89');

	filter = filter.or('vpnConfiguration.forwardingPorts.internalPort', '30219');
	
	wedeploy.data('https://<my-data>.wedeploy.io')
    .where(filter)
    .count() // --- without this, no error
    .get('foo')
    .then(function(resp){
    	res.send(resp);
    })
    .catch(function(err){
    	res.send(err);
    });

});
```
The error is:

```
/home/rafael/dev/we-deploy/test/node_modules/metal/lib/async/async.js:26
		throw exception;
		^
RangeError: Invalid status code: 1
    at ServerResponse.writeHead (_http_server.js:194:11)
    at ServerResponse._implicitHeader (_http_server.js:185:8)
    at write_ (_http_outgoing.js:632:9)
    at ServerResponse.end (_http_outgoing.js:751:5)
    at ServerResponse.send (/home/rafael/dev/we-deploy/test/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/home/rafael/dev/we-deploy/test/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/home/rafael/dev/we-deploy/test/node_modules/express/lib/response.js:158:21)
    at /home/rafael/dev/we-deploy/test/index.js:25:10
    at callbackEntry.onRejected (/home/rafael/dev/we-deploy/test/node_modules/metal-promise/lib/CancellablePromise.js:822:33)
    at Function.CancellablePromise.invokeCallback_ (/home/rafael/dev/we-deploy/test/node_modules/metal-promise/lib/CancellablePromise.js:1122:30)

```
Thanks

**Comment by ipeychev** [comment]
To unblock you - you may use the following short variant, which works fine:
```
data
    .where('vpnConfiguration.forwardingPorts.host', '=', '192.168.0.3')
    .where('vpnConfiguration.forwardingPorts.port', '=', '89')
    .or('vpnConfiguration.forwardingPorts.internalPort', '=', '30219')
    .count()
    .get('foo')
    .then(function(resp) {
      console.log(resp);
    }).catch(function(err){
      console.log('ERROR!', error);
    });
```

I will take a look on the other variant too.

**Comment by ipeychev** [comment]
@rafakwolf The other variant seems to work fine too:
```
const WeDeploy = require('wedeploy');
  const data = WeDeploy.data('data-testbasicexpressapp.wedeploy.io');

  let filter = WeDeploy.Filter.equal('vpnConfiguration.forwardingPorts.host', '192.168.0.3')
                          .and('vpnConfiguration.forwardingPorts.port', '89');

  filter = filter.or('vpnConfiguration.forwardingPorts.internalPort', '30219');

  data.where(filter)
    .count()
    .get('foo')
    .then(function(resp){
      console.log(resp);
    })
    .catch(function(err){
      console.log('ERROR', error);
    });
```

Response is `0` in this case, as it should be.

Maybe the error you get is somewhere else and not in the SDK?

**Comment by ipeychev** [comment]
@rafakwolf Did you check the above comments? What is the status of this issue?

**Comment by rafakwolf** [comment]
@ipeychev like you said, possibly it is something locally, not the sdk, so i'll close the issue.
Thanks
